"""Leakage-safe foundations for PrevOccupAI muscleBAN HAR experiments."""

from .calibration import (
    CalibrationBin,
    CalibrationEvaluation,
    CalibrationFitPurpose,
    CalibrationFitScope,
    TemperatureScalingModel,
    evaluate_calibration,
    fit_temperature_scaling,
    probabilities_from_logits,
)
from .dataset import (
    DatasetAssemblyPurpose,
    DevelopmentFoldTensors,
    WindowDataset,
    assemble_development_fold_tensors,
    build_window_dataset,
)
from .evaluation import (
    PredictionEvaluation,
    confusion_matrix_from_predictions,
    evaluate_predictions,
    metrics_from_confusion_matrix,
)
from .holdout import HoldoutEvaluationPolicy, load_holdout_evaluation_policy
from .model_selection import (
    ConservativeSelectionRule,
    DevelopmentSelectionPlan,
    ModelSelectionBundle,
    SelectionCandidate,
    SelectionFold,
    SelectionRunEvidence,
    build_development_selection_plan,
    build_model_selection_bundle,
    load_development_selection_plan,
    load_model_selection_bundle,
    write_development_selection_plan,
    write_model_selection_bundle,
)
from .opensignals import (
    OpenSignalsAccelerometerHeader,
    OpenSignalsAccelerometerRecording,
    load_opensignals_accelerometer,
    read_opensignals_accelerometer_header,
    unsigned_adc_to_acceleration_m_s2,
)
from .preprocessing import TrainOnlyChannelStandardizer
from .protocol import ProtocolConfiguration, WindowSpecification, load_protocol
from .quality import (
    AccelerometerQualityReport,
    AxisQualityReport,
    QualityAssessmentConfiguration,
    QualityStatus,
    QualityThresholds,
    assess_accelerometer_quality,
    assess_axis_quality,
    load_quality_configuration,
)
from .signal_preprocessing import (
    PreprocessedAccelerometerSegment,
    SignalPreprocessingConfiguration,
    load_signal_preprocessing_configuration,
    preprocess_accelerometer_segment,
)
from .segmentation import (
    ActivitySegmentationProtocol,
    GovernedSegmentInterval,
    RawSegmentInterval,
    SegmentationContractConfiguration,
    SegmentationPurpose,
    build_governed_segment_intervals,
    load_segmentation_contract_configuration,
)
from .splits import SubjectPartition, build_validation_folds
from .statistical_evaluation import (
    ExactParticipantBootstrapInterval,
    PairedParticipantComparison,
    ParticipantBootstrapInterval,
    compare_paired_participant_metrics,
    exact_participant_bootstrap_mean_interval,
    exact_paired_sign_flip_p_value,
    holm_adjust,
    participant_bootstrap_mean_interval,
)
from .temporal_evaluation import (
    TemporalConsistencyMetrics,
    TemporalPredictionEvaluation,
    evaluate_temporal_predictions,
)
from .windowing import WindowMetadata, create_windows, iter_window_bounds

__all__ = [
    "AccelerometerQualityReport",
    "ActivitySegmentationProtocol",
    "AxisQualityReport",
    "CalibrationBin",
    "ExactParticipantBootstrapInterval",
    "CalibrationEvaluation",
    "CalibrationFitPurpose",
    "CalibrationFitScope",
    "DatasetAssemblyPurpose",
    "DevelopmentFoldTensors",
    "DevelopmentSelectionPlan",
    "HoldoutEvaluationPolicy",
    "ModelSelectionBundle",
    "OpenSignalsAccelerometerHeader",
    "OpenSignalsAccelerometerRecording",
    "PairedParticipantComparison",
    "ParticipantBootstrapInterval",
    "PredictionEvaluation",
    "ProtocolConfiguration",
    "PreprocessedAccelerometerSegment",
    "QualityAssessmentConfiguration",
    "QualityStatus",
    "QualityThresholds",
    "GovernedSegmentInterval",
    "RawSegmentInterval",
    "SegmentationContractConfiguration",
    "SegmentationPurpose",
    "SelectionCandidate",
    "SelectionFold",
    "SelectionRunEvidence",
    "SignalPreprocessingConfiguration",
    "SubjectPartition",
    "TemperatureScalingModel",
    "TemporalConsistencyMetrics",
    "TemporalPredictionEvaluation",
    "TrainOnlyChannelStandardizer",
    "WindowDataset",
    "WindowMetadata",
    "WindowSpecification",
    "ConservativeSelectionRule",
    "assess_accelerometer_quality",
    "assess_axis_quality",
    "assemble_development_fold_tensors",
    "build_window_dataset",
    "build_validation_folds",
    "build_governed_segment_intervals",
    "build_development_selection_plan",
    "build_model_selection_bundle",
    "compare_paired_participant_metrics",
    "confusion_matrix_from_predictions",
    "create_windows",
    "evaluate_predictions",
    "evaluate_temporal_predictions",
    "evaluate_calibration",
    "exact_participant_bootstrap_mean_interval",
    "exact_paired_sign_flip_p_value",
    "holm_adjust",
    "fit_temperature_scaling",
    "iter_window_bounds",
    "load_holdout_evaluation_policy",
    "load_development_selection_plan",
    "load_model_selection_bundle",
    "load_protocol",
    "load_quality_configuration",
    "load_signal_preprocessing_configuration",
    "load_segmentation_contract_configuration",
    "load_opensignals_accelerometer",
    "metrics_from_confusion_matrix",
    "participant_bootstrap_mean_interval",
    "probabilities_from_logits",
    "preprocess_accelerometer_segment",
    "read_opensignals_accelerometer_header",
    "unsigned_adc_to_acceleration_m_s2",
    "write_development_selection_plan",
    "write_model_selection_bundle",
]
